# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarSim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='x',
            field=models.FloatField(default=20000000000.0),
        ),
        migrations.AddField(
            model_name='planet',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='planet',
            name='z',
            field=models.FloatField(default=0),
        ),
    ]
